### ISSUE TITLE
Coinomi HD-derived ETH addresses are different from Coleman's tool

### ISSUE THREAD

**Issue by avibrazil** [iancoleman/bip39#143] opened 2017-12-07 00:22 UTC
While BTC, BCH and a few other tested coins have same addresses on Coleman's and on Coinomi wallet, ETH addresses do not match.

Please install their Android wallet and use same phrase+password as in Coleman't tool to reproduce the problem. They have an online tool to generate addresses at https://coinomi.com/recovery-phrase-tool.html

Cross reference bug report: https://coinomi.freshdesk.com/support/tickets/871069

I'm opening bug reports here and in Coinomi's web site because I don't know where is the problem.
There is also a chance that I'm doing something wrong, then I'll appreciate some enlightenment.

Thank you in advance.

**Comment by iancoleman** [comment] 2017-12-07 02:18
Duplicate of https://github.com/iancoleman/bip39/issues/128

**Closed by iancoleman** 2017-12-07 02:18 UTC
