### ISSUE TITLE
wrong xpriv key for japanese mnemonic

### ISSUE THREAD

**Issue by mpolci** [iancoleman/bip39#60] opened 2017-03-02 10:11 UTC
I tested the site using mnemonic and passphrases from test vector at https://github.com/bip32JP/bip32JP.github.io/blob/master/test_JP_BIP39.json

I always obtained a different xpriv key. For example the first element of test vector is:
```
{
       "entropy": "00000000000000000000000000000000",
       "mnemonic": "あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あいこくしん　あおぞら",
       "passphrase": "メートルガバヴァぱばぐゞちぢ十人十色",
       "seed": "a262d6fb6122ecf45be09c50492b31f92e9beb7d9a845987a02cefda57a15f9c467a17872029a9e92299b5cbdf306e3a0ee620245cbd508959b6cb7ca637bd55",
       "bip32_xprv": "xprv9s21ZrQH143K258jAiWPAM6JYT9hLA91MV3AZUKfxmLZJCjCHeSjBvMbDy8C1mJ2FL5ytExyS97FAe6pQ6SD5Jt9SwHaLorA8i5Eojokfo1"
},
```

but the web site for this mnemonic and passphrase returns:
```
seed: 46f8c196417a09a1dfdff5824538098509f99cc4f291acc3d77a4d0a3edde480806141c82b73102db2e05c21ba7a1aa46a2b3e12efba1c082773eacb657518d7
root key: xprv9s21ZrQH143K2oyoD9x9rxhdUmfzcDhCXA8UUHeSvJh6tU37dHjK8ncouWeLBbLt2G8QEtNtbztRX8KWp2huTCscBtJh9PWYZWH6qKfhr9u
```

**Comment by iancoleman** [comment] 2017-03-02 22:17
Thanks for this.

It turned out to be a bug with https://github.com/iancoleman/jsbip39 - and the bug wasn't detected because of a second bug in the test suite for that library.

This has been fixed now.

See
* https://github.com/iancoleman/jsbip39/commit/fb6c333ae034b6cef74c64d91d5488a9ed4fd87b - Tests for various languages fixed
* https://github.com/iancoleman/jsbip39/commit/200912564fc709d78a440f41a0dc5405ab76dd95 - Mnemonic normalization is correct
* https://github.com/iancoleman/bip39/commit/599fb39e4e775c4f972ecfa3a9c4548177c23183 - jsbip39 updated - fixes Japanese language
* https://github.com/iancoleman/bip39/commit/d2d98ef7a6b859ea173d044677e0b1abf1dceb41 - Regression test for seed from Japanese mnemonic

**Closed by iancoleman** 2017-03-02 22:17 UTC
