### ISSUE TITLE
1st Ethereum address not displayed using some mnemonic phrases ?

### ISSUE THREAD

**Issue by apzoei** [iancoleman/bip39#155] opened 2018-01-11 04:13 UTC
Hi,

To verify some mnemonics generated with Ledger wallet, I used the BIP39 tool, and MyEtherWallet. Then I compared the addresses generated for Bitcoin and Ethereum.

All addresses were matching, but I have noticed that for one mnemonic, the 1st Ethereum address shown in the BIP39 tool is the second one in MEW (the 1st address in MEW is the one displayed with Ledger Chrome wallet)

With the other mnemonics, the BIP39 tool displays Ethereum addresses list starting with path `m/44'/60'/0'/0`, but with that one it starts with path `m/44'/60'/0'/1`.

The mnemonic is :
`scout sort custom elite radar rare vivid thing trophy gesture cover snake change narrow kite list nation sustain buffalo erode open balance system young`

Ledger Chrome wallet displays Ethereum address as :
`0x8943E785B4a5714FC87a3aFAad1eB1FeB602B118`

MyEtherWallet displays :
`0x8943E785B4a5714FC87a3aFAad1eB1FeB602B118`
`0xB3678B6b0446e2F97E3Ef6e34F02F78B9485bB6d` ...

BIP 39 tool diplays (with Ledger's BIP32 Derivation Path `m/44'/60'/0'`) : 
`m/44'/60'/0'/1` (<- starting with 1 not 0) : `0xB3678B6b0446e2F97E3Ef6e34F02F78B9485bB6d`
`m/44'/60'/0'/2` : `0x3d05E0383797e8b9d8D290C5B8087ceAC0434e3F` ...

Hope this was helpful.

**Comment by iancoleman** [comment] 2018-01-11 23:27
Can you please confirm this? I can't reproduce the issue.

I use these steps:

1. Set mnemonic to `scout sort custom elite radar rare vivid thing trophy gesture cover snake change narrow kite list nation sustain buffalo erode open balance system young`
1. Change coin to ethereum
1. See first address in the table is `m/44'/60'/0'/0/0   0xc426c3b767498be6299099ea6E9B4dfC2673A812` which does not match the reported address or path in this issue.

What browser are you using?

**Comment by apzoei** [comment] 2018-01-12 18:49
I am using Chrome and I confirm this.

You got `m/44'/60'/0'/0/0 | 0xc426c3b767498be6299099ea6E9B4dfC2673A812` because you were in the `BIP44` tab.

You have to switch to `BIP32` tab.

The steps:

1. Set mnemonic to `scout sort custom elite radar rare vivid thing trophy gesture cover snake change narrow kite list nation sustain buffalo erode open balance system young`
2. Change coin to Ethereum
3. Switch to `BIP32` tab
4. Change `BIP32` Derivation Path to `m/44'/60'/0'` (used in Ledger)
5. First address in the table is `m/44'/60'/0'/1(one) | 0xB3678B6b0446e2F97E3Ef6e34F02F78B9485bB6d` which should be `m/44'/60'/0'/0(zero) | 0x8943E785B4a5714FC87a3aFAad1eB1FeB602B118` not shown

This address is obtened with both Ledger and MyEtherWallet selecting Ledger (ETH) `m/44'/60'/0'` as HD derivation path.

**Comment by iancoleman** [comment] 2018-01-15 22:00
Seems to be an error in ethereumjs-util.js when calling

```
var addressBuffer = ethUtil.privateToAddress(privKeyBuffer);

Error
ethereumjs-util.js:17200 Uncaught RangeError: private key length is invalid
```

It only happens for index 0 of this mnemonic+path, and not for any other mnemonics or paths I've tried.

The invalid private key is `875133cde6416b146fde442e8accc9230a2849627ec9979f7fad3c6a5583cf`

It's because the key is 31 bytes. It's missing a leading `0` byte. The valid key is `00875133cde6416b146fde442e8accc9230a2849627ec9979f7fad3c6a5583cf`

This involves modifying the `privKeyBuffer` on [index.js L802](https://github.com/iancoleman/bip39/blob/de8e5bc11fb7024ee403db7931e3ae082d7f968e/src/js/index.js#L802) to be 32 bytes instead of 31 by padding with a leading 0.

It can be fixed by passing in the 'size' value to `toBuffer()`, ie `toBuffer(32)`. I'll commit this change and include it in the next release.

Thanks for reporting this. Good find!

**Comment by iancoleman** [comment] 2018-01-15 23:35
See https://github.com/iancoleman/bip39/commit/78db37f6636f195753a59a61901f850880177c50

**Closed by iancoleman** 2018-01-15 23:35 UTC
