### ISSUE TITLE
Nano Derivation Method

### ISSUE THREAD

**Issue by Babuxor** [iancoleman/bip39#472] opened 2021-02-24 01:12 UTC
The same BIP39 Mnemonic phrase (24 words) generated different nano keys in Trust Wallet and Natrium. With some research I found on tools.nano that nano keys can be derivated in different ways: Ledger/Magnum (BIP39/44) used here and on Trust wallet and Blake2b used on Natrium, Exodus and probably others wallets. 
It is possible to add a choice to select a method or the other one?
I tried to do it myself but failed.

**Comment by loupiote** [comment] 2021-04-21 09:19
See https://github.com/iancoleman/bip39/issues

**Comment by iancoleman** [comment] 2021-05-06 23:49
Duplicate of #490 - let's track it all in that topic. I'm sure we can add some improvement to the ui to make this situation clearer for nano users.

**Closed by iancoleman** 2021-05-06 23:49 UTC
